### ISSUE TITLE
setup.py Error

### ISSUE THREAD

**Issue by itsLeonR** [Hundemeier/sacn#1]
Error with your setup.py. If you install it with pip3, the following Error occues. 

Command :
pip3 install setup.py

Output: 
Collecting setup.py
Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py

**Comment by Hundemeier** [comment]
The solution is very simple:
go to your folder were the setup.py file is and execute 'pip install .'
If you want to install only symlinks to the files in the directory (eg you want to modify the files and don't want to reinstall all the time) use 'pip install -e .'

For more information on pip installation see: https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree
