### ISSUE TITLE
sender[] indexes are universe IDs

### ISSUE THREAD

**Issue by johnemajor** [Hundemeier/sacn#12]
It was not completely obvious from the example in the readme that the array indexes in 'sender' were the universe id's specified in sender.activate_output(#).  It took me a bit of puzzling to figure that out.  Please consider clarifying this in the Readme.

Otherwise, this library is a lifesaver and helps me get around some serious limitations I was hitting with OLA (namely that they keep you to <= 32 universes!).

Thanks for writing this.

jem

**Comment by Hundemeier** [comment]
Isn't the sentence found below the [example](https://github.com/Hundemeier/sacn#sending-1) enough?

You can activate an output universe via `activate_output(<universe>)` and then change the attributes of this universe via `sender[<universe>].<attribute>`.
