### ISSUE TITLE
HowTo use the library

### ISSUE THREAD

**Issue by Cyb0rg42** [Hundemeier/sacn#16]
Hi, 
I want to use the library to send DMX commands to a WiFi ACN controller. I have 2 universes enabled on the WiFi controller. There are icicles connected to the controller. 
When I sent DMX data to the controller only the first led will be turned on. There are 300 channels per universe. Can you supply me with a sender[n].dmx_data example to turn on, for instance, the 16th led? 

Thanks...
Karl

**Comment by Hundemeier** [comment]
Without knowing the DMX-Mapping of the fixture your guess is as good as mine.
If the fixtures are non-RGB and are using one LED per DMX-Channel, that would be `(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)`?

**Comment by Cyb0rg42** [comment]
I want to control icicles with the sacn library. The setup I have is a sACN compitable WiFi controller with 7 universes. On every universe there is one icicle connected (https://www.aliexpress.com/item/4000079959915.html?spm=a2g0o.productlist.0.0.6b1e16f2PhmTWY&algo_pvid=c1c6c1b2-8fa1-459b-a4b8-f757310f8d6b&algo_expid=c1c6c1b2-8fa1-459b-a4b8-f757310f8d6b-1&btsid=fe06a66a-2301-4b85-b860-fe3a42474065&ws_ab_test=searchweb0_0,searchweb201602_9,searchweb201603_53). The leds are RGB leds. , no extra white led. If I want to turn them all on what should be the content of sender(n).dmx)data.  The controller I am using is https://www.aliexpress.com/item/32545202529.html?spm=a2g0o.productlist.0.0.2d4f7c93nmr2Y2&algo_pvid=fa91aadd-c7e9-47bf-a029-7486cfafbf21&algo_expid=fa91aadd-c7e9-47bf-a029-7486cfafbf21-0&btsid=e5f416ae-8f1f-47cb-a3b7-f32c7ef8fa11&ws_ab_test=searchweb0_0,searchweb201602_9,searchweb201603_53.

Thanks 
Karl

**Comment by Cyb0rg42** [comment]
Got it working: sender[1].dmx_data((1,1,1)*180)

Thanks for the support
