### ISSUE TITLE
Dropping a network link with transmitting data is unrecoverable

### ISSUE THREAD

**Issue by andrewyager** [Hundemeier/sacn#48]
We've just identified an issue when an sACN Node is directly connected to our transmitter.

In https://github.com/Hundemeier/sacn/blob/042968632deb914ed98b310762852778ace9994c/sacn/sending/sender_socket_udp.py#L96

the exception of being unable to transmit is caught, but never passed upstream to allow the code to be able to detect that the socket has been closed and take appropriate action (for instance, reconnect, or other).

**Comment by Hundemeier** [comment]
Good catch! This was not intended behavior and should have been handled similarly to https://github.com/Hundemeier/sacn/blob/master/sacn/sending/sender_socket_udp.py#L37-L39

I've released `v1.9.1` that fixes this bug.
