### ISSUE TITLE
Receiving issue

### ISSUE THREAD

**Issue by Elsurimi** [Hundemeier/sacn#9]
Hi, 
Thanks for your library it's a good job. But I have a problem with the receiving fonction on a rasberry pi.

When I try your example no packet are detected, but when I look with Tshark,  packets from my sacn controller are send:

Capturing on 'eth0.5'
    1 0.000000000 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
    2 0.000223900 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638
    3 0.806439562 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
    4 0.806614974 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638
    5 1.613344715 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
    6 1.613531325 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638
    7 2.421833872 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
    8 2.422283339 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638
    9 3.229036949 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
   10 3.229303036 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638
   11 4.033248002 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
   12 4.033428361 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638
   13 4.840318954 192.168.13.200 → 239.255.0.2  UDP 680 48369 → 5568 Len=638
   14 4.840480148 192.168.13.200 → 239.255.0.3  UDP 680 48369 → 5568 Len=638

Do you know where is the problem?

Thanks

**Comment by Hundemeier** [comment]
Sorry for the late reply.
Your sender is sending out the data as multicast (universes 2 and 3). Did you setup the receiving according to the [guide](https://github.com/Hundemeier/sacn#receiving-1)? Note the remarks on joining multicast universes.
